### ISSUE TITLE
constexpr support?

### ISSUE THREAD

**Issue by expnkx** [jk-jeon/dragonbox#12]
With C++20 std::bit_cast, bit (std::rotr, std::rotl) and std::is_constant_evaluated(), it should be possible to do this at compile time.

You can guard your code with feature testing macros.

https://en.cppreference.com/w/cpp/feature_test#:~:text=Language%20features%20%20%20%20Macro%20name%20,%20%20%28C%2B%2B11%29%20%2027%20more%20rows%20

BTW, compiler specific attributes can be replaced with [[gnu::xxxx]] or [[msvc::xxxxx]]

**Comment by jk-jeon** [comment]
This sounds reasonable.
The only problem is that
(1) Implementations of bit manipulation intrinsics seem to be suboptimal so far, and
(2) Sadly, feature testing macros are not well supported by many currently-widely-used compiler versions.
At some point in the future, probably I will change the target language version to C++20.
These things might be adapted after that.
Anyway, thanks for the suggestion!
