### ISSUE TITLE
Suggest to use C++ attribute instead of compiler extension attributes for forceinline stuffs

### ISSUE THREAD

**Issue by expnkx** [jk-jeon/dragonbox#13]
```cpp
#if __has_cpp_attribute(gnu::always_inline)
[[gnu::always_inline]]
#elif __has_cpp_attribute(msvc::forceinline)
[[msvc::forceinline]]
#endif
inline
```
inline keyword has nothing to do with inlining in C++. It means mr. compiler please do not violate ODR.

**Comment by jk-jeon** [comment]
This sounds reasonable, but I think the benefit is marginal. Of course everyone (including me) hates macros, but current usages of macros has little possibility to cause any problem (I believe), and also it does not leak outside the header file. So I think this change just unnecessarily makes the code more verbose.
