### ISSUE TITLE
warning for -Wpedantic, ISO C++ does not support '__int128' for 'type name'

### ISSUE THREAD

**Issue by expnkx** [jk-jeon/dragonbox#16]
ISO C++ does not support '__int128' for 'type name' [-Wpedantic]
  341 |         return (unsigned __int128)(x) * (unsigned __int128)(y);

**Comment by expnkx** [comment]
https://github.com/expnkx/fast_io/commit/699850c4cb73e521a364bbbdbb443f7c054002f5

**Comment by jk-jeon** [comment]
It seems like the warning is generated even when `__int128` is available. In that case the only solution I can think of is to either (1) ignore the warning or (2) disable the warning. Do you have any suggestion?

**Comment by expnkx** [comment]
see my commit.

**Comment by jk-jeon** [comment]
You mean, to change `unsigned __int128` to `__uint128`m

**Comment by expnkx** [comment]
yes

**Comment by expnkx** [comment]
btw, you do not need to guard against x86. __uint128_t exists on other architectures too.

**Comment by jk-jeon** [comment]
Thanks for the suggestion. But it seems `unsigned __int128` is an older thing than `__uint128_t`. Why the former generates a warning while the latter doesn't? Is the latter supposed to replace the former? If that's the case, do I need to version-check gcc/clang?

**Comment by jk-jeon** [comment]
Okay, so according to https://stackoverflow.com/questions/16088282/is-there-a-128-bit-integer-in-gcc, it's the other way around: `unsigned __int128` is the new one, and it's the recommended one which is meant to replace `__uint128_t`. It's strange that `unsigned __int128` generates a warning while `__uint128_t` doesn't.

>btw, you do not need to guard against x86. __uint128_t exists on other architectures too.

I believe I addressed this issue in the commit https://github.com/jk-jeon/dragonbox/commit/4032d671c375ac2475bc9a41b042b72d2a646c60.

**Comment by jk-jeon** [comment]
Fixed.
