### ISSUE TITLE
Invalid template parameters when using toward_minus_infinity and toward_plus_infinity

### ISSUE THREAD

**Issue by mrmixer** [jk-jeon/dragonbox#26]
Trying to compile the following code, I get an error on line 2058, where the second parameter passed to `divide_by_pow10` is `significand_bits + kappa + 2` instead of `carrier_uint` or something similar. I also assume the 3rd parameter isn't the correct value.

```cpp
#include "dragonbox.h"

int main( int argc, char** argv ) {
    
    float x = 1.234f;   
    auto v = jkj::dragonbox::to_decimal( x, jkj::dragonbox::policy::decimal_to_binary_rounding::toward_plus_infinity );
    return 0;
}
```

Compiling with MSVC: cl -nologo main.cpp -Fe:dragonbox.exe -Zi -Od -std:c++17

**Comment by jk-jeon** [comment]
Thanks a lot for catching this!
Fixed in 02059bdee06beb9fea28a399e6463d1d1f8edbfa.
Now `v` is set to be `{12339999, -7}`.
