### ISSUE TITLE
Typos in the paper

### ISSUE THREAD

**Issue by DanShaders** [jk-jeon/dragonbox#34]
It seems that there should be no "= \varnothing" at the beginning of the second column on page 10.
![typo1](https://user-images.githubusercontent.com/30951924/199575673-ed766bd7-84ae-4396-a3c7-a61d7b6c0849.png)
And no "-s" in "ingredients", likewise no "-o" in "computationo".
![typo2](https://user-images.githubusercontent.com/30951924/199575880-f0b28e4b-29d3-4539-b27c-b0d4e6f9ffb3.png)

As we are already talking about the article, how is this fact at the very end of the first column on page 9 being used later in the proof?
![image](https://user-images.githubusercontent.com/30951924/199576490-33d83453-d1b5-4d7b-a9ac-68f430322eef.png)

**Comment by DanShaders** [comment]
> The claim "Clearly, in this case we should have n1<n2..." follows from the said inequality.

Got it. I cannot say it is that "clear" then)

Thank you!

**Comment by DanShaders** [comment]
Oops

**Comment by jk-jeon** [comment]
Uploaded the fixed one.

>Got it. I cannot say it is that "clear" then)

Also made this really clear :)
