### ISSUE TITLE
Source code incomprehensible

### ISSUE THREAD

**Issue by DanielBaumert** [jk-jeon/dragonbox#40]
Hello :D

Can you briefly explain why you do these checks?
https://github.com/jk-jeon/dragonbox/blob/34a6cdf99d4afe18008877627dabe1f5bf238e1a/source/dragonbox_to_chars.cpp#L80-L82

**Comment by jk-jeon** [comment]
@Alcaro Thanks for the information, it seems I was over-cautious. Let's remove it then.
