### ISSUE TITLE
`to_decimal` regressed since last November

### ISSUE THREAD

**Issue by DanShaders** [jk-jeon/dragonbox#48]
```cpp
double x = 1.234;
auto v = jkj::dragonbox::to_decimal(x);
std::cout << v.significand << std::endl;
```
outputs `1234000000000000` instead of `1234`. I am not sure if this is intended or not, but it is an example from readme, so either readme should be fixed or something is wrong with the code.

I noticed this when tried to update Dragonbox from 33a9e021290d529bcb41773be2c7c3c91726a9cb to the current master in the stress of SerenityOS's Ryu implementation.

**Comment by jk-jeon** [comment]
Thanks for catching this!
