### ISSUE TITLE
nvcc (Version 201402L) throws "error: namespace "std" has no member "is_same_v"

### ISSUE THREAD

**Issue by dirk8b** [jk-jeon/dragonbox#49]
Hi,
I am trying to test dragonbox with the nvcc compiler (Version 201402L). 
But it throws; 
1. dragonbox/dragonbox_to_chars.h(98): error: namespace "std" has no member "is_same_v" std::is_same_v<FloatFormat, ieee754_binary32>
2. dragonbox/dragonbox_to_chars.h(98): error: type name is not allowed std::is_same_v<FloatFormat, ieee754_binary32>
3. dragonbox/dragonbox_to_chars.h(98): error: expected a ";" std::is_same_v<FloatFormat, ieee754_binary32>

I only include dragonbox_to_chars.h in my test code (I have to write millions of float numbers to a csv file with high performance. std::to_string and fprintf are far to slow.).

In my understanding and looking into the dragonbox code it should work with this nvcc version. 

Where is the knot in the head?

Thank you!

**Comment by jk-jeon** [comment]
The library used to require C++17. I recently did some big overhaul to make it C++11 compatible, but this was a thing that I missed. With the recent commit [9a7e3fc](https://github.com/jk-jeon/dragonbox/commit/9a7e3fcc7a9796f814f49353fa6aff2637b044c7) this should have fixed now.

Thank you for reporting the issue, and please feel free to post additional compatibility issues if you find anything.

**Comment by dirk8b** [comment]
Thank you, but there are warnings and errors again:

- dragonbox_to_chars.h(97): warning #3033-D: inline variables are a C++17 feature inline constexpr std::size_t max_output_string_length = detected during instantiation of "const std::size_t jkj::dragonbox::max_output_string_length [with FloatFormat=jkj::dragonbox::ieee754_binary64]"
- warning #174-D: expression has no effect jkj::dragonbox::max_output_string_length<jkj::dragonbox::ieee754_binary64>;
- warning #174-D: expression has no effect jkj::dragonbox::max_output_string_length<jkj::dragonbox::ieee754_binary64>;
- /tmp/tmpxft_0000270a_00000000-11_SchreibTest.o: in function `char* jkj::dragonbox::to_chars_detail::to_chars_n_impl<jkj::dragonbox::detail::policy_impl::policy_holder<jkj::dragonbox::detail::policy_impl::decimal_to_binary_rounding::nearest_to_even, jkj::dragonbox::detail::policy_impl::binary_to_decimal_rounding::to_even, jkj::dragonbox::detail::policy_impl::cache::full>, double, jkj::dragonbox::default_float_traits<double> >(jkj::dragonbox::float_bits<double, jkj::dragonbox::default_float_traits<double> >, char*)':
- tmpxft_0000270a_00000000-6_SchreibTest.cudafe1.cpp:(.text._ZN3jkj9dragonbox15to_chars_detail15to_chars_n_implINS0_6detail11policy_impl13policy_holderIJNS4_26decimal_to_binary_rounding15nearest_to_evenENS4_26binary_to_decimal_rounding7to_evenENS4_5cache4fullEEEEdNS0_20default_float_traitsIdEEEEPcNS0_10float_bitsIT0_T1_EESF_[_ZN3jkj9dragonbox15to_chars_detail15to_chars_n_implINS0_6detail11policy_impl13policy_holderIJNS4_26decimal_to_binary_rounding15nearest_to_evenENS4_26binary_to_decimal_rounding7to_evenENS4_5cache4fullEEEEdNS0_20default_float_traitsIdEEEEPcNS0_10float_bitsIT0_T1_EESF_]+0x152): undefined reference to `char* jkj::dragonbox::to_chars_detail::to_chars<double, jkj::dragonbox::default_float_traits<double> >(jkj::dragonbox::default_float_traits<double>::carrier_uint, int, char*)'
- collect2: error: ld returned 1 exit status

I have a very tiny testcode (no output so far) for this:
int main() {
constexpr int buffer_length = 21;
jkj::dragonbox::max_output_string_length<jkj::dragonbox::ieee754_binary64>;
double x = 1.234;
char buffer[buffer_length];
char* end_ptr = jkj::dragonbox::to_chars(x, buffer);
}

I will use a lookup table for the conversion now. I think there is no faster way if the numbers are very limited (-1000.00 till + 1000.00 in my case). 

Have a nice weekend

**Comment by jk-jeon** [comment]
I believe the recent commit (b5ba69256b00d35f3f3df79042600fdf41098f88) now fixed it. Thank you very much for the report!
