### ISSUE TITLE
x86(Win32) on MSVC 2019 reporting roundtrip errors

### ISSUE THREAD

**Issue by yumeyao** [jk-jeon/dragonbox#5]
I used https://github.com/jk-jeon/dtoa-benchmark to build a win32 exe straight forward from the vs 2019 sln file, and find out dragonbox is corrupted on win32 at the moment. I also tried overwriting dragonbox.h in benchmark project with the latest file from this repository, still no help.

To reproduce:

- clone dtoa-benchmark, and open it in vs 2019
- fix win32 include path (a pull request is there in the benchmark repo)
- comment out milo_only_grisu2.cpp REGISTER_TEST(...) line (it's very slow or maybe dead-loop?)
- build & run

**Comment by jk-jeon** [comment]
Thanks so much for reporting this issue! It seems like a bug in `countr_zero` implementation. I will fix it soon and commit the change.

As a side note: I don't recommend my implementation of Dragonbox for 32-bit applications, especially with MSVC. It will be very slow compared to the 64-bit counterpart. It seems that MSVC is really poor at optimizing 64-bit arithmetic operations/bit manipulations when compiled with the 32-bit mode. (It seems that MSVC **NEVER** inlines 64-bit multiplications, for example.) But it's up to you. I recommend you to do benchmarks yourself for that case to figure out what's the best option.

**Comment by jk-jeon** [comment]
Fixed with the commit https://github.com/jk-jeon/dragonbox/commit/2bc30d2b405fbd2a53eecaeae1bb91ad0b9e69a5.

**Comment by yumeyao** [comment]
as a respond to the sidenote:
in MSVC win32 mode, there is a [__emul(u)](https://docs.microsoft.com/en-us/cpp/intrinsics/emul-emulu?view=vs-2019) intrinsic that multiplies 2 32-bit (unsigned) integer into a 64-bit (unsigned) integer. also it seems the compiler is not smart enough to figure out `uint64_t mask = (uint64_t(1) << 32) - 1; //use full & mask;`, I suggest in such case you direct cast it to uint32_t, i.e. use `(uint32_t) full` to replace `full & mask`.

I was modifying the code and applied several x86_32 intrinsics and I found the bug is gone (yes I optimized `countr_zero`, and as a side effect I fixed the bug :) ).

and now the speed ratio against other algorithms on win32 is on par with that on win64. I can clean the code up and file a pull request later. specifically, on this i3-9100T CPU, from:
```
Benchmarking randomdigit dragonbox            ... [  92.657ns,  108.261ns]
Benchmarking randomdigit dragonbox_comp       ... [ 136.737ns,  154.552ns]
Benchmarking randomdigit grisu_exact          ... [ 108.781ns,  161.247ns]
Benchmarking randomdigit floaxie              ... [  76.074ns,  201.620ns]
```
to:
```
Benchmarking randomdigit dragonbox            ... [  73.464ns,   98.685ns]
Benchmarking randomdigit dragonbox_comp       ... [ 109.997ns,  121.866ns]
Benchmarking randomdigit grisu_exact          ... [  95.581ns,  136.788ns]
Benchmarking randomdigit floaxie              ... [  74.739ns,  204.203ns]

```
(floaxie added as it runs fastest among other algorithms)

and an extra sidenote:
you can always split up the unsupported 64-bit intrinsics on 32-bit platform into 2 supported 32-bit intrinsics.

**Comment by jk-jeon** [comment]
Wow. Looks great. I am looking forward your PR😍
