### ISSUE TITLE
Wrong constant?

### ISSUE THREAD

**Issue by gifti258** [jk-jeon/dragonbox#55]
In line 832 of dragonbox.h there is a right shift of 7 bits, whereas in the paper it is a right shift of 71 bits (section 5.1.7). It seems that 71 is indeed correct.

**Comment by Alcaro** [comment]
That is a shift by 71. The remaining 64 bits are in the umul128_upper64; that function multiplies, then shifts the return value by 64.

But yes, it certainly _looks_ wrong to the uninitaited.

**Comment by gifti258** [comment]
Oh, my bad! Thanks!
